name: trying_redux
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_redux: ^0.6.0
  redux: ^4.0.0+3
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true